# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: ci-test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    
    - name: Set up Go 1.2x
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'
      id: go  

    - name: Checkout out code into the Go Module directory  
    - uses: actions/checkout@v4

    - name: Test
      run: go test -v ./...
